MLD/MLD/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    # path('', include('MLD_app.urls')),
    path('', include(('MLD_app.urls', 'MLD_app'), namespace='MLD_app')),
    path('home/<value>', TemplateView.as_view(template_name='view_images.html')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MLD/MLD_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

urlpatterns = [
     path('home/', views.class_view, name='home'),
     path('home/<value>', views.frames_display, name='view_images')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MLD/MLD_app/models.py
from django.db import models

# Create your models here.

MLD/MLD_app/views.py
from django.shortcuts import render
from rest_framework.decorators import api_view
from MLD import settings
from MLD_app import py_model
import os


# Create your views here.


def class_view(request):
    context = {
        'class_data': py_model.Dropdwn_class()
    }

    return render(request, 'home.html', context=context)


@api_view(['GET'])
def frames_display(request, value):
    a = py_model.selectedimg(value)
    path = settings.MEDIA_ROOT
    img_list = os.listdir(path + '\\' + value) if value == "laptop" or value == 'person' else []
    context = {
        'user_val': value,
        'images': img_list,
        'media_url': settings.MEDIA_URL
    }
    print()

    return render(request, 'view_images.html', context=context)

MLD/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <style>
  h3 a{
	float:right;
  }
  h3{
    margin-left:90%;
  }
  p{
     margin-left:14%;
  }
  .header {
	background-color: silver;
  }
  .content{
	font-size: xxx-large;
  }
  form button{
	margin-left: 27%;
  }
  .col-md-3{
     margin-bottom: 10%;
	 margin-top: 10%;
   }
  .dropbtn {
	  background-color: #4CAF50;
	  color: white;
	  padding: 16px;
	  font-size: 16px;
	  border: none;
	  cursor: pointer;
	}

	.dropbtn:hover, .dropbtn:focus {
	  background-color: #3e8e41;
	}

	#myInput {
	  box-sizing: border-box;
	  background-image: url('searchicon.png');
	  background-position: 14px 12px;
	  background-repeat: no-repeat;
	  font-size: 16px;
	  padding: 14px 20px 12px 45px;
	  border: none;
	  border-bottom: 1px solid #ddd;
	}

	#myInput:focus {outline: 3px solid #ddd;}

	.dropdown {
	  position: relative;
	  display: inline-block;
	  max-width: 170px;
	  min-width: 130px;
	}

	.dropdown-content {
	  display: none;
	  position: absolute;
	  background-color: #f6f6f6;
	  min-width: 130px;
	  overflow: auto;
	  border: 1px solid #ddd;
	  z-index: 1;
	  overflow: auto;
	  max-width: 170px;
	  max-height: 250px;
	}

	.dropdown-content a {
	  color: black;
	  padding: 12px 16px;
	  text-decoration: none;
	  display: block;
	  max-height:250px;
	  overflow:auto;
	}

	.dropdown a:hover {background-color: #ddd;}

	.show {display: block;}
  </style>
  <meta charset="utf-8">
  <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" rel="stylesheet"/>
</head>
<body>
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>
</body>
</html>

MLD/templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
	<div class="row header">
	<h2>Hi {{ user.username }}!</h2> <h3><a href="{% url 'logout' %}">Log Out</a></h3>
	</div>
	<div class="row">
		<div class="col-md-3">
			<div class="dropdown">
			<button onclick="myFunction()" id= "dropbtn" class="dropbtn">Choose an Image!</button>
			
			<div id="myDropdown" class="dropdown-content">
				<input type="text" placeholder="Search.." id="myInput" onkeyup="filterFunction()"/>
				{% for class_values in class_data %}
					<a onclick ="img_select(this)" id="{{class_values}}" href='{{class_values}}'>{{class_values}}</a>
				{% endfor %}
				<!--<a href="#about">About</a>
				<a href="#base">Base</a>
				<a href="#blog">Blog</a>
				<a href="#contact">Contact</a>
				<a href="#custom">Custom</a>
				<a href="#support">Support</a>
				<a href="#tools">Tools</a>-->
			</div>
			</div>
		</div>
		{% block image %}
		{% endblock %}
	</div>
	
	<script src="http://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>

	<script>
		function myFunction() {
		  document.getElementById("myDropdown").classList.toggle("show");
		}
		function img_select(ele){
			var image = $(ele).attr('id');
			localStorage.setItem('Img_name',image);
			$("#myDropdown").hide();
		}
		document.getElementById("dropbtn").onclick = function(){
			var txt = document.getElementById('dropbtn').innerHTML;
			if (txt == 'Back to list' ){
				document.getElementById('dropbtn').innerHTML='Choose an Image!';
				$("#myDropdown").show();
				//myFunction();
				var url = "{% url 'MLD_app:home' %}";
				document.location.href = url;
			}
			else{
				myFunction();
			}
					
		}
		$(window).on('load', function() {
			if(window.location.pathname != "/home/"){
				document.getElementById('dropbtn').innerHTML='Back to list';
			}
		});
		function filterFunction() {
		  var input, filter, ul, li, a, i;
		  input = document.getElementById("myInput");
		  filter = input.value.toUpperCase();
		  div = document.getElementById("myDropdown");
		  a = div.getElementsByTagName("a");
		  for (i = 0; i < a.length; i++) {
			txtValue = a[i].textContent || a[i].innerText;
			if (txtValue.toUpperCase().indexOf(filter) > -1) {
			  a[i].style.display = "";
			} else {
			  a[i].style.display = "none";
			}
		  }
		}

  </script>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">Log In</a>
{% endif %}
{% endblock %}

MLD/templates/view_images.html
{% extends 'home.html' %}


<!--{{media_url}}{{user_val}}{{image}}.jpg-->
{% block image %}
{% if user_val == "laptop" or user_val == "person" %}
	<div class="col-md-9">
		<div class="row content">Displaying the {{user_val}} image </div>
		{% for i in "x"|rjust:"1" %}
			<div class="row">
				{% for image in images %}
			
					<div class="col-md-3"><img src="{{media_url}}{{user_val}}/{{image}}" alt="{{user_val}}" width="150" height="150"> </div>
				{% endfor %}
			</div>
		{% endfor %}
	</div>
{% else %}
  <div class="row">There is no {{user_val}} image to display </div>
  <!--<a href="{% url 'MLD:home' %}">Back to List</a>-->
{% endif %}

{% endblock %}